-- Cuantos trabajadores tiene cada jefe

SELECT
    J.NOMBRE, COUNT(T.NOMBRE) "NUM EMPLEADOS"
FROM
    TRABAJADOR T
    JOIN TRABAJADOR J
    ON J.TRABAJADOR_ID=T.JEFE_ID
GROUP BY J.NOMBRE
ORDER BY 2;