DROP TABLE CLIENTE CASCADE CONSTRAINTS;

CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER(10) CONSTRAINT PK_CLIENTE PRIMARY KEY,
    DNI VARCHAR2(9) CONSTRAINT UQ_DNI_CLIENTE UNIQUE,
    NOMBRE VARCHAR2(50),
    FECHAALTA DATE DEFAULT SYSDATE
);