/* 
 * Las siguientes definiciones de tablas corresponderían a un esquema en el cual una persona puede tener varias aficiones
 * y una afición puede ser compartida por varias personas.
*/

DROP TABLE PERSONA CASCADE CONSTRAINT;

DROP TABLE AFICION CASCADE CONSTRAINT;

DROP TABLE PERSONA_AFICION CASCADE CONSTRAINT;

CREATE TABLE PERSONA (
    ID_PERSONA NUMBER(4),
    NOMBRE VARCHAR2(50),
    CONSTRAINT PK_PERSONA PRIMARY KEY (ID_PERSONA)
);

CREATE TABLE AFICION (
    ID_AFICION NUMBER(4),
    DESCRIPCION VARCHAR2(50),
    CONSTRAINT PK_AFICION PRIMARY KEY (ID_AFICION)
);

CREATE TABLE PERSONA_AFICION (
    ID_PERSONA NUMBER(4),
    ID_AFICION NUMBER(4),
    CONSTRAINT PK_PERSONA_AFICION PRIMARY KEY (ID_PERSONA, ID_AFICION),
    CONSTRAINT FK_PERSONA FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA(ID_PERSONA),
    CONSTRAINT FK_AFICION FOREIGN KEY (ID_AFICION) REFERENCES AFICION(ID_AFICION)
);