DROP TABLE CLIENTE CASCADE CONSTRAINTS;

CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER(10),
    DNI VARCHAR2(9),
    NOMBRE VARCHAR2(50),
    FECHAALTA DATE DEFAULT SYSDATE,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT UQ_DNI_CLIENTE UNIQUE (DNI)
);