CREATE TABLE TRABAJADOR (
	TRABAJADOR_ID NUMBER (4),
	NOMBRE VARCHAR2 (15),
	JEFE_ID NUMBER (4),
	CONSTRAINT PK_TRABAJADOR PRIMARY KEY (TRABAJADOR_ID),
	CONSTRAINT FK_TRABAJADOR_TRABAJADOR_ID FOREIGN KEY (JEFE_ID) REFERENCES TRABAJADOR (TRABAJADOR_ID)
);

CREATE TABLE ALOJAMIENTO (
	ALOJAMIENTO_ID NUMBER (2),
	ALOJAMIENTO CHAR(15),
	NOMBRECOMPLETO CHAR(40),
	RESPONSABLE CHAR(25),
	DIRECCION CHAR(30),
	DISTANCIA NUMBER,
	CONSTRAINT PK_ALOJAMIENTO PRIMARY KEY (ALOJAMIENTO_ID)
);

CREATE TABLE OFICIO (
	OFICIO_ID NUMBER (2),
	OFICIO CHAR(25),
	DESCRIPCION CHAR(80),
	CONSTRAINT PK_OFICIO PRIMARY KEY (OFICIO_ID)
);

CREATE TABLE EMPLEADO (
	EMPLEADO_ID NUMBER (2),
	NOMBRE CHAR(25),
	EDAD NUMBER,
	ALOJAMIENTO NUMBER (2),
	SUELDO NUMBER (5, 2),
	CONSTRAINT PK_EMPLEADO PRIMARY KEY (EMPLEADO_ID),
	CONSTRAINT FK_EMPLEADO_ALOJAMIENTO FOREIGN KEY (ALOJAMIENTO) REFERENCES ALOJAMIENTO (ALOJAMIENTO_ID)
);

CREATE TABLE OFICIOEMPLEADO (
	EMPLEADO NUMBER (2),
	OFICIO NUMBER (2),
	CALIFICACION CHAR(15),
	CONSTRAINT PK_OFICIOEMPLEADO PRIMARY KEY (EMPLEADO, OFICIO),
	CONSTRAINT FK_OFICIOEMPLEADO_EMPLEADO FOREIGN KEY (EMPLEADO) REFERENCES EMPLEADO (EMPLEADO_ID),
	CONSTRAINT FK_OFICIOEMPLEADO_OFICIO FOREIGN KEY (OFICIO) REFERENCES OFICIO (OFICIO_ID)
);