SELECT
    COUNT(EMPLEADO_ID) "EMPLEADOS POR ALOJAMIENTO",
    A.ALOJAMIENTO
FROM
    EMPLEADO E, ALOJAMIENTO A
WHERE
    E.ALOJAMIENTO=ALOJAMIENTO_ID
GROUP BY
    A.ALOJAMIENTO
ORDER BY
    "EMPLEADOS POR ALOJAMIENTO";
    