SELECT
    COUNT(E.NUMEMP) AS CUANTOS
FROM
    EMPLEADO       E
    JOIN OFICIOEMPLEADO OE
    ON E.NUMEMP=OE.EMPLEADO
    JOIN OFICIO O
    ON OE.OFICIO=O.NUMOFICIO
WHERE
    E.EDAD > 66
    AND O.OFICIO = 'OBRERO';