/* 
 * No me gusta el nombre de la tabla Empleado, renombra esa tabla a Empleada sin perdida de restricciones
 * incluyendo FK y PK
*/

ALTER TABLE OFICIOEMPLEADO DROP CONSTRAINT FK_OFICIOEMPLEADO_EMPLEADO;

RENAME EMPLEADO TO EMPLEADA;

ALTER TABLE OFICIOEMPLEADO ADD CONSTRAINT FK_OFICIOEMPLEADA_EMPLEADA FOREIGN KEY (EMPLEADO) REFERENCES EMPLEADA(EMPLEADO_ID);