/*
 * ¿Que alojamiento tiene mas empleados? Con mostrar el primero es mas que suficiente.
 * Se debe mostrar el nombre del alojamiento y el numero de empleados.
*/

SELECT
    A.NOMBRECOMPLETO,
    COUNT(E.EMPLEADO_ID) AS "TOTAL DE EMPLEADOS"
FROM
    ALOJAMIENTO A
    JOIN EMPLEADA E
    ON A.ALOJAMIENTO_ID = E.ALOJAMIENTO
GROUP BY
    A.NOMBRECOMPLETO
-- HACEMOS UN HAVING PARA EVITAR QUE SOLO MUESTRE UN REGISTRO SI HAY VARIOS CON EL MISMO VALOR MAXIMO
HAVING COUNT(E.EMPLEADO_ID) = (
    SELECT
        MAX(COUNT(E.EMPLEADO_ID))
    FROM
        ALOJAMIENTO A
        JOIN EMPLEADA E
        ON A.ALOJAMIENTO_ID = E.ALOJAMIENTO
    GROUP BY
        A.NOMBRECOMPLETO
    FETCH FIRST ROW ONLY
)
ORDER BY
    "TOTAL DE EMPLEADOS" DESC;