DROP TABLE ACTOMEDICO CASCADE CONSTRAINT;

DROP TABLE COMPANIA CASCADE CONSTRAINT;

DROP TABLE TARIFA CASCADE CONSTRAINT;

CREATE TABLE ACTOMEDICO (
    ID_ACTOMEDICO NUMBER(4),
    DESCRIPCION VARCHAR2(50),
    PRECIO_ACTOMEDICO NUMBER,
    CONSTRAINT PK_ACTOMEDICO PRIMARY KEY (ID_ACTOMEDICO)
);

CREATE TABLE COMPANIA (
    ID_COMPANIA NUMBER(4),
    NOMBRE VARCHAR2(15),
    CONSTRAINT PK_COMPANIA PRIMARY KEY (ID_COMPANIA)
);

CREATE TABLE TARIFA (
    ID_ACTOMEDICO NUMBER(4),
    ID_COMPANIA NUMBER(4),
    PRECIO NUMBER,
    CONSTRAINT PK_TARIFA PRIMARY KEY (ID_ACTOMEDICO, ID_COMPANIA),
    CONSTRAINT FK_TARIFAACTOMEDICO FOREIGN KEY (ID_ACTOMEDICO) REFERENCES ACTOMEDICO(ID_ACTOMEDICO),
    CONSTRAINT FK_TARIFACOMPANIA FOREIGN KEY (ID_COMPANIA) REFERENCES COMPANIA(ID_COMPANIA)
);