DROP TABLE ACTOMEDICO CASCADE CONSTRAINT;
DROP TABLE COMPANIA CASCADE CONSTRAINT;
DROP TABLE TARIFA CASCADE CONSTRAINT;


CREATE TABLE ACTOMEDICO (
    ID_ActoMedico NUMBER(4),
    Descripcion VARCHAR2(50),
    Precio_ActoMedico NUMBER,
    CONSTRAINT PK_ActoMedico PRIMARY KEY (ID_ActoMedico)
);

CREATE TABLE COMPANIA (
    ID_Compania NUMBER(4),
    Nombre VARCHAR2(15),
    CONSTRAINT PK_Compania PRIMARY KEY (ID_Compania)
);

CREATE TABLE TARIFA (
    ID_ActoMedico NUMBER(4),
    ID_Compania NUMBER(4),
    Precio NUMBER,
    CONSTRAINT PK_Tarifa PRIMARY KEY (ID_ActoMedico, ID_Compania),
    CONSTRAINT FK_TarifaActoMedico FOREIGN KEY (ID_ActoMedico) REFERENCES ActoMedico(ID_ActoMedico),
    CONSTRAINT FK_TarifaCompania FOREIGN KEY (ID_Compania) REFERENCES COMPANIA(ID_Compania)
);