CREATE OR REPLACE PROCEDURE ASIGNAPLAZASFOR AS
  CURSOR C_SOL(
    P_ESTU ESTUDIANTE.IDESTUDIANTE%TYPE
  ) IS
  SELECT
    *
  FROM
    SOLICITA
  WHERE
    IDESTUDIANTE=P_ESTU
  ORDER BY
    PREFERENCIA;
  CURSOR C_EST IS
  SELECT
    *
  FROM
    ESTUDIANTE
  ORDER BY
    NOTAMEDIA DESC,
    NOMBRE;
  TOTALPLAZAS          NUMBER;
  SINPLAZA             BOOLEAN;
  PLAZASCICLOOFERTADAS NUMBER;
  PLAZASCICLOASIGNADAS NUMBER;
BEGIN
  SELECT
    SUM(PLAZAS) INTO TOTALPLAZAS -- TOTAL PLAZAS OFERTADAS.
  FROM
    OFERTAEDUCATIVA;
  DELETE FROM ASIGNACION;
  COMMIT;
  FOR V_ESTU IN C_EST LOOP
    FOR V_SOL IN C_SOL(V_ESTU.IDESTUDIANTE) LOOP
      SELECT
        PLAZAS -- OFERTA DE PLAZAS DEL CICLO SOLICITADO
        INTO PLAZASCICLOOFERTADAS
      FROM
        OFERTAEDUCATIVA
      WHERE
        IDIES=V_SOL.IDIES
        AND IDCICLO=V_SOL.IDCICLO
        AND IDTURNO=V_SOL.IDTURNO;
      SELECT
        COUNT(*) INTO PLAZASCICLOASIGNADAS -- PLAZAS YA ASIGNADAS
      FROM
        ASIGNACION
      WHERE
        IDIES=V_SOL.IDIES
        AND IDCICLO=V_SOL.IDCICLO
        AND IDTURNO=V_SOL.IDTURNO;
      IF PLAZASCICLOASIGNADAS<PLAZASCICLOOFERTADAS THEN -- SI QUEDAN PLAZAS POR ASIGNAR
        TOTALPLAZAS:=TOTALPLAZAS-1;
        INSERT INTO ASIGNACION -- HA CONSEGUIDO PLAZA
        VALUES(
          V_SOL.IDESTUDIANTE,
          V_SOL.IDIES,
          V_SOL.IDCICLO,
          V_SOL.IDTURNO
        );
        EXIT; -- SALIMOS PARA PROCESAR EL SIGUIENTE ESTUDIANTE
      END IF;
    END LOOP;

    IF TOTALPLAZAS=0 THEN
      EXIT;
    END IF;
  END LOOP;

  COMMIT;
END ASIGNAPLAZASFOR;