-- Obtener los nombres de los empleados de los que tenemos algún oficio registrado.

-- CON SUBCONSULTA Y EXISTS
SELECT
    NOMBRE
FROM
    EMPLEADO
WHERE
    EXISTS (
        SELECT
            EMPLEADO
        FROM
            OFICIOEMPLEADO
        WHERE
            OFICIOEMPLEADO.EMPLEADO=EMPLEADO.EMPLEADO_ID
    );

-- CON JOIN
SELECT
    DISTINCT NOMBRE
FROM
    EMPLEADO
    JOIN OFICIOEMPLEADO
    ON OFICIOEMPLEADO.EMPLEADO=EMPLEADO.EMPLEADO_ID;

-- CON WHERE
SELECT
    DISTINCT NOMBRE
FROM
    EMPLEADO,
    OFICIOEMPLEADO
WHERE
    OFICIOEMPLEADO.EMPLEADO=EMPLEADO.EMPLEADO_ID;