-- Obtener el nombre y alojamiento de los empleados hospedados en ‘CRAMMER’

SELECT
    NOMBRE,
    ALOJAMIENTO.ALOJAMIENTO
FROM
    EMPLEADO,
    ALOJAMIENTO
WHERE
    EMPLEADO.ALOJAMIENTO=ALOJAMIENTO_ID
    AND ALOJAMIENTO.ALOJAMIENTO='CRAMMER';

-- CON JOIN

SELECT
    NOMBRE,
    ALOJAMIENTO.ALOJAMIENTO
FROM
    EMPLEADO
    JOIN ALOJAMIENTO
    ON EMPLEADO.ALOJAMIENTO=ALOJAMIENTO_ID
WHERE
    ALOJAMIENTO.ALOJAMIENTO='CRAMMER';