-- Queremos obtener el nombre de los conductores de segadora que estén alojados en la ciudad de EDMESTON.

-- CON WHERE
SELECT
    NOMBRE
FROM
    EMPLEADO,
    OFICIO,
    OFICIOEMPLEADO,
    ALOJAMIENTO
WHERE
    EMPLEADO_ID=OFICIOEMPLEADO.EMPLEADO
    AND OFICIO_ID=OFICIOEMPLEADO.OFICIO
    AND OFICIO.OFICIO='CONDUCTOR DE SEGADORA'
    AND EMPLEADO.ALOJAMIENTO=ALOJAMIENTO_ID
    AND DIRECCION LIKE '%EDMESTON%';

-- CON JOIN
SELECT
    NOMBRE
FROM
    ALOJAMIENTO
    JOIN EMPLEADO
    ON ALOJAMIENTO_ID=EMPLEADO.ALOJAMIENTO
    JOIN OFICIOEMPLEADO
    ON EMPLEADO_ID=EMPLEADO
    JOIN OFICIO
    ON OFICIO_ID=OFICIOEMPLEADO.OFICIO
WHERE
    OFICIO.OFICIO='CONDUCTOR DE SEGADORA'
    AND DIRECCION LIKE '%EDMESTON%';

-- CON SUBCONSULTA
SELECT
    NOMBRE
FROM
    EMPLEADO
WHERE
    ALOJAMIENTO= ANY(
        SELECT
            ALOJAMIENTO_ID
        FROM
            ALOJAMIENTO
        WHERE
            DIRECCION LIKE '%EDMESTON%'
    )
    AND EMPLEADO_ID= ANY(
        SELECT
            EMPLEADO
        FROM
            OFICIOEMPLEADO
        WHERE
            OFICIO=(
                SELECT
                    OFICIO_ID
                FROM
                    OFICIO
                WHERE
                    OFICIO='CONDUCTOR DE SEGADORA'
            )
    );